"""add user password

Revision ID: 19a0e24ea220
Revises: 09815479f9c7
Create Date: 2025-12-16 11:12:29.775627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a0e24ea220'
down_revision: Union[str, Sequence[str], None] = '09815479f9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False, server_default=""))
    # ### end Alembic commands ###

    # 清掉 default（只用來過 migration）
    op.alter_column('users', 'password_hash', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
