"""add price and discount to discounts

Revision ID: 3b16c94e74c9
Revises: da12b74d8227
Create Date: 2025-12-13 21:57:10.742153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b16c94e74c9'
down_revision: Union[str, Sequence[str], None] = 'da12b74d8227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('discounts', sa.Column('discount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounts', 'discount')
    op.drop_column('discounts', 'price')
    # ### end Alembic commands ###
