"""add user role

Revision ID: 57128841f773
Revises: 19a0e24ea220
Create Date: 2025-12-17 08:29:40.961387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '57128841f773'
down_revision: Union[str, Sequence[str], None] = '19a0e24ea220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = postgresql.ENUM('user', 'admin', name='userrole')
    userrole.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('role', userrole, nullable=False, server_default='user'))
    
    # 加完後把 default 拿掉（避免 DB 層永遠綁死 default）
    op.alter_column('users', 'role', server_default=None)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
